apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbrella-artifacts-pvc
  namespace: umbrella-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
